// Code generated by mockery v2.42.0. DO NOT EDIT.

package controllers

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// MockPageControllers is an autogenerated mock type for the PageControllers type
type MockPageControllers struct {
	mock.Mock
}

type MockPageControllers_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPageControllers) EXPECT() *MockPageControllers_Expecter {
	return &MockPageControllers_Expecter{mock: &_m.Mock}
}

// HomePageController provides a mock function with given fields: c
func (_m *MockPageControllers) HomePageController(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for HomePageController")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPageControllers_HomePageController_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HomePageController'
type MockPageControllers_HomePageController_Call struct {
	*mock.Call
}

// HomePageController is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockPageControllers_Expecter) HomePageController(c interface{}) *MockPageControllers_HomePageController_Call {
	return &MockPageControllers_HomePageController_Call{Call: _e.mock.On("HomePageController", c)}
}

func (_c *MockPageControllers_HomePageController_Call) Run(run func(c echo.Context)) *MockPageControllers_HomePageController_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *MockPageControllers_HomePageController_Call) Return(_a0 error) *MockPageControllers_HomePageController_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPageControllers_HomePageController_Call) RunAndReturn(run func(echo.Context) error) *MockPageControllers_HomePageController_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPageControllers creates a new instance of MockPageControllers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPageControllers(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPageControllers {
	mock := &MockPageControllers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
